### ISSUE TITLE
Modify gecko code to improve annotation specifically for annotating Linda's audio lectures.

### ISSUE THREAD

**Issue by DougrZ** [LET-Voice-Annotation/let-gecko#15]

**Comment by DougrZ** [comment]
- [ ] Add additional playback rates
- [ ] Display time code in seconds for 
- [ ] Find and annotate all punctuation as PUNCTATION

**Comment by isohedral** [comment]
I think the ultimate feature for reviewing the transcript would be a keyboard shortcut that advances to the next WORD, underlines it, plays it, and stops.  In an ideal world, you'd be able to just hit that button repeatedly, and watch and hear each word as it comes up. How feasible is that?

**Comment by DougrZ** [comment]
It's probably feasible, and I'll have a look. I don't think it's going to be a quick fix though. 

I have been using the 2 new features with background color and hover times and things are going pretty well. For the most part the ASR gets things right, and when it doesn't, things seem to be glaringly wrong. 

I have not been trying to change where the ASR determined a word started or ended for each word and second guessing the ASR result. If words are grouped or broken or missing then of course that needs to be fixed.

**Comment by isohedral** [comment]
ASR is generally OK. I was using Unit 4a as a test, and unfortunately the detection of the word "Humes" in the very first section of text is wayyy off. That makes me nervous about what other ill-timed detections we might find.  Unfortunately, detecting that a word's start or end times is off by watching the interface play out the audio is hard.

**Comment by DougrZ** [comment]
I can see that particular detection is a problem and there are likely more like it. 

Perhaps there's room for QA script or another function in `preproc.py`?  The word "Humes" lasts only 0.01 seconds in the annotation far too short of a time to be valid. Perhaps a script that flags words that have times that unrealistic wrt. the number of characters. Perhaps a check for some minimum and maximum time per letter?

**Comment by isohedral** [comment]
I don't know if number of characters is a good measure, but generally speaking something like this would be easy and worthwhile. The two obvious approaches are:

 * Pick a global threshold for how short we think a word can be in time. Anything below this threshold is considered suspicious.
 * In each transcript, compute the standard deviation of word durations. Flag as suspicious any words that are too far below (or above!) this duration.

This would interact in a funny way with compounds (multiple words in a single token, which my scripts separates).  We basically don't want to flag compounds as too long or too short, because we know there's already something wrong with them. But we also don't want to analyze the individual words they get split into, because we invent times for those words, and know they're wrong. So in flagging word durations as suspicious, we'd basically skip anything that came from a compound.

**Comment by DougrZ** [comment]
You've given this more thought than I have. Your ideas sound good, do you want to do it.

**Comment by isohedral** [comment]
This is a bit more fiddly than I expected. I've got a prototype in the checked-in version of preproc.py, but it doesn't do anything yet (apart from hiding its own work).

**Comment by DougrZ** [comment]
Just to make clear for this issue. The work that was initially being discussed here as changes to Gecko in this repository were implemented as a prototype in the preproc.py script which is in the [LET-Voice-Annotation/let-voice](https://github.com/LET-Voice-Annotation/let-voice), which is a private repository and cannot be accessed by not team members. However this let-gecko repository in a clone of the original [gong-io/gecko](https://github.com/gong-io/gecko) and is public.
